// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBriJi5iuzp1LGjFVXg8PjeDfYvqiRjuiQ',
    appId: '1:457712394889:web:2495fa50373cda5f569c58',
    messagingSenderId: '457712394889',
    projectId: 'warehousepro-20f46',
    authDomain: 'warehousepro-20f46.firebaseapp.com',
    storageBucket: 'warehousepro-20f46.firebasestorage.app',
    measurementId: 'G-5LPY5D9DC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuJAquuQcEc_U9hvPoVi3XegGQRX54DV4',
    appId: '1:457712394889:android:67bff93974cc0422569c58',
    messagingSenderId: '457712394889',
    projectId: 'warehousepro-20f46',
    storageBucket: 'warehousepro-20f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0_G3ybHSKwDsd3WNt0Qn9Bawtgg4DI24',
    appId: '1:457712394889:ios:281d625a3bc06af3569c58',
    messagingSenderId: '457712394889',
    projectId: 'warehousepro-20f46',
    storageBucket: 'warehousepro-20f46.firebasestorage.app',
    iosBundleId: 'com.warehousepro.warehouseproDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0_G3ybHSKwDsd3WNt0Qn9Bawtgg4DI24',
    appId: '1:457712394889:ios:281d625a3bc06af3569c58',
    messagingSenderId: '457712394889',
    projectId: 'warehousepro-20f46',
    storageBucket: 'warehousepro-20f46.firebasestorage.app',
    iosBundleId: 'com.warehousepro.warehouseproDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBriJi5iuzp1LGjFVXg8PjeDfYvqiRjuiQ',
    appId: '1:457712394889:web:840ba9578feffa47569c58',
    messagingSenderId: '457712394889',
    projectId: 'warehousepro-20f46',
    authDomain: 'warehousepro-20f46.firebaseapp.com',
    storageBucket: 'warehousepro-20f46.firebasestorage.app',
    measurementId: 'G-G6R1T3NX03',
  );
}
